### ISSUE TITLE
Imagen clase en resoluciones altas

### ISSUE THREAD

**Issue by ivojawer** [uqbar-project/website-wollok-ts#16]
Esta imagen: https://github.com/uqbar-project/website-wollok-ts/blob/b7a675bd6c9423655b682422273a34e7f86b2aad/src/assets/clase.jpeg

Es de tamaño [1866 × 1048] 

En el codigo:
https://github.com/uqbar-project/website-wollok-ts/blob/b7a675bd6c9423655b682422273a34e7f86b2aad/src/content/components/landing-page/pedagogical-tool/PedagogicalTool.astro#L7

El elemento `Image` que la esta mostrando para no deformar la imagen esta setteando el tamaño, este es el elemento html que se termina renderizando:
```html
<img 
  src="/website-wollok-ts/_astro/clase.hNnFFwEO_JozGx.webp" 
  class="class-img astro-pwl3u3hu" 
  alt="Wollok en la clase" 
  width="1866" 
  height="1048" 
  loading="lazy" 
  decoding="async"
>
```

esto hace que en resoluciones mas grandes se termine viendo una barra al costado 😢 

Habria dos opciones:
- ver como overridear el atributo `width` de la imagen
- conseguir una version con mejor resolucion

**Comment by fdodino** [comment]
@ivojawer @PalumboN creo que esto quedó deprecado
