### ISSUE TITLE
Tener una consola interactiva

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/website-wollok-ts#18]
Yo tendría la consola como se ve actualmente
<img width="839" alt="image" src="https://github.com/uqbar-project/website-wollok-ts/assets/4098184/ce20c026-85b6-41b9-b322-e7c12170d2c5">

Con 3 tabs: código, diagrama y consola (+ botón `Recargar` *).

Al levantar la página se levanta un REPL con el código, el diagrama está conectado a esa sesión y la consola interactúa con eso.
Uno podría interactuar en la consola y revisar el diagrama / código todo lo que quiera.

*) Cuando se **cambia el código** se activa el botón de Recargar para reiniciar la sesión del REPL con el nuevo código (`:rr`) (y por ende se reinicia el diagrama y se limpia el historial de la consola)

**Comment by estefaniamiguel** [comment]
buenas, no estoy viendo donde sería esto... en qué sección...

**Comment by fdodino** [comment]
@estefaniamiguel , esto iría en la página principal. Ya hicimos un par de cambios en base a este issue: https://github.com/uqbar-project/wollok-ts-cli/issues/149. La idea es que les chiques puedan escribir código wollok en la web, con un IDE muy básico para probar cositas.

**Comment by fdodino** [comment]
Cierro el issue porque ya tenemos una implementación activa.
