### ISSUE TITLE
Se detectan errores en código comentado

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/website-wollok-ts#29]
Son extraños los lugares donde se muestra un error en codigo comentario. 
Al intentar reproducirlo, se da en la 3° o posterior línea de un comentario (no antes), previo a la llave de cierre de la definición de un objeto. Tambien dentro de un metodo, pero no entre un método y otro.

![image](https://github.com/uqbar-project/website-wollok-ts/assets/11738011/4105e323-2a3b-455c-ad98-cc4a4270d40b)

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok-ts/issues/207

**Comment by PalumboN** [comment]
@lspigariol esto debería estar solucionado después de https://github.com/uqbar-project/wollok-ts/pull/251

Ya hay varios issues relacionados (y yo vine con ganas de cerrar :P) así que voy a cerrar esto y te pido que pruebes con la próxima versión del LSP y si encontrás algún problema vuelvas a abrir un issue.

Graciela :)
