### ISSUE TITLE
Mejoras a la página de documentación

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/website-wollok-ts#3]
![image](https://github.com/uqbar-project/website-wollok-ts/assets/4549002/d1a79678-93a8-426f-9732-155b7cc4202c)

Yo solo creo que sacaría la parte derecha de sinopsis para aprovecharla y que el ancho de la parte principal (donde está la documentación) tome todo el ancho del viewport (si es mobile lo siento por ti). De paso que no lo corte:

![image](https://github.com/uqbar-project/website-wollok-ts/assets/4549002/08cd48f2-50ca-4b41-9d60-73c08f144380)

**Comment by fdodino** [comment]
Otra propuesta es que la sinopsis esté embebida dentro de la página, arriba, para que no pierdas navegabilidad pero tampoco te corte parte del ancho.

**Comment by PalumboN** [comment]
Esto está mucho mejor después de https://github.com/uqbar-project/website-wollok-ts/pull/31 🚀 

Cierro y cualquier cosa abrimos otro.

> Otra propuesta es que la sinopsis esté embebida dentro de la página, arriba, para que no pierdas navegabilidad pero tampoco te corte parte del ancho.

Cuando la pantalla es chica lo hace automágicamente el template.
