### ISSUE TITLE
mas detalle en las indicaciones de instalacion

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/website-wollok-ts#4]
se le puede dar caracter de "necesario" a cagregar al PATH la carpeta. Las explicaciones de cómo hacerlo seria mejor que esten en el mismo sitio (y en argentino)
En linux hay que agregar el paso de darle permiso de ejecución al archivo
Tambien esta bueno ser mas insistente en el paso de cambiarle el nombre al archivo del ejecutable  por wollok. Así, quedan más consistentes los ejemplos siguientes de uso del repl

**Comment by fdodino** [comment]
Bueno, 95% de las cosas ya fueron resueltas con el PR #19  y el 5% restante lo tratamos de mejorar.
