### ISSUE TITLE
Strict equality(===)  in string is not function as expected  

### ISSUE THREAD

**Issue by LGaliz** [uqbar-project/website-wollok-ts#41]
![Screenshot from 2024-09-16 20-05-41](https://github.com/user-attachments/assets/17a4638d-2c0f-46b2-a8aa-f2253439f636)

Result shoud be false
https://www.wollok.org/documentation/advanced/#identidad-vs-igualdad

**Comment by PalumboN** [comment]
En esta discusión: https://github.com/uqbar-project/wollok-language/issues/199 acordamos cambiar la documentación para que no hable de la identidad de objetos "primitivos" sino con propios objects.

La identidad de los números y strings queda en función de la VM y siempre debe respetar lo que muestra el diagrama de objetos.

**Comment by fdodino** [comment]
Cierro el issue porque actualizamos la página para mostrar un ejemplo con un mail, que representa un Value Object. También está actualizado el apunte.
