### ISSUE TITLE
nuevo proyecto

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/website-wollok-ts#5]
Buscaria la forma de no asumir que el estudiante sepa trabajar con una terminal. Probablemente, para muchos la única terminal que conocen o van a conocer en la materai es la que esta dentro del VSC. Veria de explicar cómo crear el proyecto desde alli y luego abrir la nueva ubicación. 

la consulta por la version no me parece necesario en ese lugar

tener una carpeta creada y vacia puede ponerse como pre-requisito más que como paso

**Comment by fdodino** [comment]
Crear el proyecto desde la terminal de VSC puede resultar más confuso, ahí agregué cómo levantar una terminal desde cero, porque si no van a tener que levantar otro VSC para abrir el proyecto. El resto lo corregí tal cual lo decía el ticket.
