### ISSUE TITLE
WollokDoc "Documentation not found"  on several game methods.

### ISSUE THREAD

**Issue by isaiaslafon** [uqbar-project/website-wollok-ts#53]
En https://www.wollok.org/documentation/language/#wollok.game.game hay varios métodos que tienen Doumentation not found.

https://github.com/uqbar-project/wollok-site/blob/master/documentacion/wollokdoc/game.html
![image](https://github.com/user-attachments/assets/c1f47ced-9e18-46c5-bb81-c21e5f9008d3)
![image](https://github.com/user-attachments/assets/09fcd692-9d4b-4d5c-8d22-52df77ce0370)
![image](https://github.com/user-attachments/assets/3e0c1ded-f16e-4ca4-af9d-5d1d37f294c1)

**Comment by isaiaslafon** [comment]
Went setting "English" as language in the web:
![image](https://github.com/user-attachments/assets/05fef8e6-a154-4d16-8a45-df8c45ab17ed)

**Comment by PalumboN** [comment]
Creo que el problema de la doc que está en el código pero no se muestra en la página viene por un bug que tenía el parser con los comentarios.

El bug ya fue arreglado, pero el sitio todavía sigue buscando la documentación en otro nodo:
https://github.com/uqbar-project/website-wollok-ts/blob/a6954ea47a874dc5ecd8b7eab0645f9ea10b0be2/src/content/components/language/utils.ts#L64-L70

Habría que borrar esa lógica y que la saque del nodo en cuestión.

**Comment by isaiaslafon** [comment]
Copado! si entendí bien aún no está solucionado, pero es un avance. Lo voy a mirar en estos días!

**Comment by fdodino** [comment]
hola @isaiaslafon @PalumboN ,
     hoy estuve en UNAHur jugando un poco y usando la metadata parseada veo que hay métodos que siguen sin tener doc:

![image](https://github.com/user-attachments/assets/2ccc89f7-8235-45c3-a759-d82915c6cf17)

![image](https://github.com/user-attachments/assets/5423d851-dfca-4939-8372-75f7302ebfee)

Si se fijan:
- hay métodos que tienen más de una metadata armada porque tienen más de un `/*  */` (private, por ejemplo), eso se puede corregir en lang
- pero me preocupa más que capitalize, take, map no tienen documentación porque el parser ignora la doc siguiente de los métodos que tienen un `=` por ejemplo `words` tiene definido

```wollok
method words() = self.split(" ")
```

eso hace que la doc de capitalize no se vea:

```wollok
/**
   * Changes the first letter of every word to
   * upper case in this string.
   *
   * Example:
   *      "javier fernandes".capitalize() ==> Answers "Javier Fernandes"
   */
```

Lo que viene parseado es...

```ts
 {
    name: 'words',
    metadata: '[{"name":"comment","args":{"text":"/**\\n   * Splits this strings into several words.\\n   *\\n   * Examples:\\n   *      \\"how does words work?\\".words()\\n   *            ==> Answers [\\"how\\", \\"does\\", \\"words\\", \\"work?\\"]\\n   *\\n   *      \\"\\".words() ==> Answers []\\n   */","position":"start"}}]'
  },
  { name: 'capitalize', metadata: '[]' },
  { name: 'initialize', metadata: '[]' },
```

**Comment by isaiaslafon** [comment]
Bien @fdodino !!! Justo estaba viendo que no tenía snetido que una esté y otra no y mirando el javadoc en sí no encontraba el problema, bien que miraste la definicion! Otros así creo que son los nativos, pero no estoy seguro.
