### ISSUE TITLE
ejercicios anteriores

### ISSUE THREAD

**Issue by lspigariol** [uqbar-project/website-wollok-ts#7]
estaria bueno una seccion que explique como abrir/cargar proyectos existentes, cerca de la de proyectos nuevos.

se puede linkear con el listado de ejemplos existentes y/o recomendados.

(y habria que validar si siguen funcionando todos... pero eso va para otro ticket)

**Comment by PalumboN** [comment]
@lspigariol Fer ya estuvo tocando esta página https://uqbar-project.github.io/website-wollok-ts/getting_started/new_project y migrando todos los ejemplos 🚀 

Decís que falta agregar algo?
